# [START app_yaml]
runtime: nodejs10
handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$
  static_files: dist/\1
  upload: dist/(.*\..+)$

  # catch all handler to index.html
- url: /.*
  static_files: client/src/index.html
  upload: client/dist/index.html

beta_settings:
  cloud_sql_instances: dialogdata:europe-north1:dialogdata-mysql
# [END app_yaml]
